order: 24
date: '2025'
title: Flap-legged gecko (Luperosaurus macgregorii)
background: "./24-artstation-flap-legged-gecko-luperosaurus-macgregorii-01.jpg"
link: https://www.artstation.com/artwork/bKzROG
subtitle: 3D project
type: 3D
description: Created in collabraotio with Digital Life 3D and University of Michigan,
  I worked on this Flap-legged gecko from a set of CT scans and image reference for
  use in research and outreach. The model was developed from a CT scan and touched-up
  with sculpting in Blender. Texturing and rendering was also done in Blender.
images:
- "./24-artstation-flap-legged-gecko-luperosaurus-macgregorii-01.jpg"
- "./24-artstation-flap-legged-gecko-luperosaurus-macgregorii-02.jpg"
- "./24-artstation-flap-legged-gecko-luperosaurus-macgregorii-03.jpg"
- "./24-artstation-flap-legged-gecko-luperosaurus-macgregorii-04.jpg"
- "./24-artstation-flap-legged-gecko-luperosaurus-macgregorii-05.jpg"
- "./24-artstation-flap-legged-gecko-luperosaurus-macgregorii-06.jpg"
- "./24-artstation-flap-legged-gecko-luperosaurus-macgregorii-07.jpg"
- "./24-artstation-flap-legged-gecko-luperosaurus-macgregorii-08.jpg"
videos: []
keywords: []
sketchfabIds:
- 1f1ac3e5ff4d42dfbc97b3c439f9fb5a
- 5addde4a2ba8456889db59d90157dc21
