order: 20
date: '2025'
title: Juvenile Green Sea Turtle
background: "./20-artstation-juvenile-green-sea-turtle-01.jpg"
link: https://www.artstation.com/artwork/9myqKR
subtitle: 3D project
type: 3D
description: A reconstructed 3D model of a juvenile green sea turtle created for scientific
  visualization and digital biodiversity projects.
images:
- "./20-artstation-juvenile-green-sea-turtle-01.jpg"
- "./20-artstation-juvenile-green-sea-turtle-02.jpg"
- "./20-artstation-juvenile-green-sea-turtle-03.jpg"
- "./20-artstation-juvenile-green-sea-turtle-04.jpg"
- "./20-artstation-juvenile-green-sea-turtle-05.jpg"
- "./20-artstation-juvenile-green-sea-turtle-06.jpg"
- "./20-artstation-juvenile-green-sea-turtle-07.jpg"
videos: []
keywords: []
sketchfabIds:
- e9d91748653145b5a3bc4e655e1c0850
- c90a930f8b2a4cc8bc516742a0df01d9
