order: 29
date: '2025'
title: Edge Wear - Shading Practice
background: "./29-artstation-edge-wear-shading-practice-01.jpg"
link: https://www.artstation.com/artwork/BzkB6
subtitle: 3D project
type: 3D
description: The first masking shader of a collection of shaders I've been working
  on for Blender. https://blendermarket.com/products/edge-wear Thanks to Mike Pan,
  Moran Goldstein, Ben Dansie and Mark T for the models.
images:
- "./29-artstation-edge-wear-shading-practice-01.jpg"
- "./29-artstation-edge-wear-shading-practice-02.jpg"
- "./29-artstation-edge-wear-shading-practice-03.jpg"
- "./29-artstation-edge-wear-shading-practice-04.jpg"
- "./29-artstation-edge-wear-shading-practice-05.jpg"
videos: []
keywords: []
