order: 25
date: '2025'
title: Hawksbill Sea Turtle (Eretmochelys imbricata)
background: "./artstation-hawksbill-sea-turtle-eretmochelys-imbricata.jpg"
link: https://www.artstation.com/artwork/on90w
subtitle: 3D project
type: 3D
description: Creating in partnership with Digital Life 3D. I was in charge of converting
  3d scans of a living Hawskbill into a fully modeled, textured, and animated virtual
  model.
images:
- "./artstation-hawksbill-sea-turtle-eretmochelys-imbricata.jpg"
videos: []
keywords: []
sketchfabIds:
- e78b4f18979440a89745f91eaefdcb6b6
- e69458ef8176402d919df421e444da86
