order: 30
date: '2025'
title: Hologram - Shading Practice
background: "./30-artstation-hologram-shading-practice-01.jpg"
link: https://www.artstation.com/artwork/Oz6ze
subtitle: 3D project
type: 3D
description: I've had this on my drive for awhile now. I finally spent some time fixed
  it up into a proper node group. https://blendermarket.com/products/hologram
images:
- "./30-artstation-hologram-shading-practice-01.jpg"
- "./30-artstation-hologram-shading-practice-02.jpg"
- "./30-artstation-hologram-shading-practice-03.jpg"
videos: []
keywords: []
