order: 27
date: '2025'
title: James River Experience Aquatic Life
background: "./27-artstation-james-river-experience-aquatic-life-01.jpg"
link: https://www.artstation.com/artwork/8eBPZw
subtitle: 3D project
type: 3D
description: Jeremy bot, Robert Gutierrez, and myself worked on this collection of
  aquatic creatures late last year for inclusion in a James River VR experience that
  demonstrates the active ecosystem under the river's surface. My role was mainly
  to work on meshes and materials for the models, as well as fine tuning animations,
  materials, and body shape for final release. The project was produced in collaboration
  with Digital Life 3d, Richard Lewis Media Group, and Maymont Nature Center.
images:
- "./27-artstation-james-river-experience-aquatic-life-01.jpg"
- "./27-artstation-james-river-experience-aquatic-life-02.jpg"
- "./27-artstation-james-river-experience-aquatic-life-03.jpg"
- "./27-artstation-james-river-experience-aquatic-life-04.jpg"
- "./27-artstation-james-river-experience-aquatic-life-05.jpg"
- "./27-artstation-james-river-experience-aquatic-life-06.gif"
- "./27-artstation-james-river-experience-aquatic-life-07.jpg"
- "./27-artstation-james-river-experience-aquatic-life-08.jpg"
- "./27-artstation-james-river-experience-aquatic-life-09.jpg"
- "./27-artstation-james-river-experience-aquatic-life-10.jpg"
- "./27-artstation-james-river-experience-aquatic-life-11.jpg"
videos: []
keywords: []
